-- ============================================
-- STJ MEDIA — TEAM MANAGEMENT
-- ============================================

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,

  name text not null,
  photo_url text,

  role text,
  work text,
  skills text,

  instagram_url text,
  linkedin_url text,

  display_order integer default 0,

  status text default 'live'
    check (status in ('live', 'archive', 'bin')),

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


-- ============================================
-- PUBLIC + ADMIN READ ACCESS
-- ============================================

grant select on table public.team_members
to anon, authenticated;


-- ============================================
-- RLS
-- ============================================

alter table public.team_members enable row level security;


-- Public website:
-- sirf LIVE members dikhaye jayenge

drop policy if exists "Anyone can view live team"
on public.team_members;

create policy "Anyone can view live team"
on public.team_members
for select
to anon, authenticated
using (status = 'live');


-- ============================================
-- ADMIN ADD
-- ============================================

drop policy if exists "Admin can add team"
on public.team_members;

create policy "Admin can add team"
on public.team_members
for insert
to authenticated
with check (true);


-- ============================================
-- ADMIN EDIT
-- ============================================

drop policy if exists "Admin can edit team"
on public.team_members;

create policy "Admin can edit team"
on public.team_members
for update
to authenticated
using (true)
with check (true);


-- ============================================
-- ADMIN DELETE
-- ============================================

drop policy if exists "Admin can delete team"
on public.team_members;

create policy "Admin can delete team"
on public.team_members
for delete
to authenticated
using (true);


-- ============================================
-- UPDATED TIME AUTOMATICALLY CHANGE
-- ============================================

create or replace function public.update_team_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists team_updated_at
on public.team_members;

create trigger team_updated_at
before update on public.team_members
for each row
execute function public.update_team_updated_at();


-- ============================================
-- STORAGE FOLDER FOR TEAM PHOTOS
-- ============================================
-- Photos STJ-MEDIA bucket ke andar:
-- team/shiv-soni.jpg
-- team/tanmay-saini.jpg
-- etc.

drop policy if exists "Admin can upload team photos"
on storage.objects;

create policy "Admin can upload team photos"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'STJ-MEDIA'
  and (storage.foldername(name))[1] = 'team'
);


drop policy if exists "Admin can update team photos"
on storage.objects;

create policy "Admin can update team photos"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'STJ-MEDIA'
  and (storage.foldername(name))[1] = 'team'
)
with check (
  bucket_id = 'STJ-MEDIA'
  and (storage.foldername(name))[1] = 'team'
);


drop policy if exists "Admin can delete team photos"
on storage.objects;

create policy "Admin can delete team photos"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'STJ-MEDIA'
  and (storage.foldername(name))[1] = 'team'
);
